
database:
  host: localhost
  port: 5432
  database: dbname
  username: root
  password: root
  table-prefix: bapp_
  # Maximum number of times postgres will try to reconnect before giving up.
  max-reconnects: 5
  # Use SSL?
  use-ssl: disabled